Repository replicatedhq/kurl.sh, pull requests merged in 2021-12, with the labels that each got.

#620 v2021-12-02-0 Release notes
  src/release-notes/v2021.12.02-0.md
Labels: peer-review-needed, type::docs

#621 Adding release notes for kURL v2021.12.08-0
  .gitignore
  src/markdown-pages/add-ons/ekco.md
  src/release-notes/v2021.12.08-0.md
Labels: peer-review-needed, type::docs

#624 Dynamically fetch installer latest from id
  src/components/Kurlsh.js
Labels: type::chore

#626 feat: 2021.12.09-0 release notes
  src/release-notes/v2021.12.09-0.md
Labels: peer-review-done

#631 Update ipv6 docs
  src/markdown-pages/install-with-kurl/ipv6.md
  src/release-notes/v2021.12.09-0.md
Labels: type::docs

#632 Release v2021.12.17-0
  src/release-notes/v2021.12.17-0.md
Labels: peer-review-done, type::docs

#635 Fix ipv6 page formatting
  src/markdown-pages/install-with-kurl/ipv6.md
Labels: type::docs

#636 Release v2021.12.17-0
  src/markdown-pages/install-with-kurl/ipv6.md
  src/release-notes/v2021.12.09-0.md
  src/release-notes/v2021.12.14-0.md
  src/release-notes/v2021.12.17-0.md
Labels: type::docs

#638 Release v2021.12.17-1
  src/release-notes/v2021.12.17-0.md
  src/release-notes/v2021.12.17-1.md
Labels: type::docs

#639 Release v2021.12.17-1
  src/markdown-pages/install-with-kurl/ipv6.md
  src/release-notes/v2021.12.17-0.md
  src/release-notes/v2021.12.17-1.md
Labels: type::docs

#641 Use newer style for release notes
  src/release-notes/v2021.12.09-0.md
  src/release-notes/v2021.12.14-0.md
  src/release-notes/v2021.12.17-0.md
  src/release-notes/v2021.12.17-1.md
  src/release-notes/v2021.12.21-0.md
Labels: peer-review-done

#633 feat: object store to pvc migrations
  src/markdown-pages/add-ons/kotsadm.md
  src/markdown-pages/add-ons/registry.md
  src/markdown-pages/add-ons/velero.md
  src/markdown-pages/install-with-kurl/removing-object-storage.md
Labels: peer-review-done, type::docs

#643 feat: v2021.12.23-0 release notes
  src/release-notes/v2021.12.23-0.md
Labels: peer-review-done, type::docs
