Repository replicatedhq/kurl.sh, pull requests merged in 2022-02, with the labels that each got.

#681 release notes for v2022.02.01-0 and other docs
  src/markdown-pages/add-ons/containerd.md
  src/markdown-pages/install-with-kurl/advanced-options.md
  src/release-notes/v2022.02.01-0.md
Labels: peer-review-done, type::docs

#682 release notes for v2022.02.01-0 and other docs (#681)
  src/markdown-pages/add-ons/containerd.md
  src/markdown-pages/install-with-kurl/advanced-options.md
  src/release-notes/v2022.02.01-0.md
Labels: type::docs

#683 Mark all CentOS versions as deprecated
  src/markdown-pages/install-with-kurl/system-requirements.md
Labels: type::docs, team::orange

#687 add release notes for the 2022-02-09 release
  src/release-notes/v2022.02.09-0.md
Labels: peer-review-needed, type::docs, team::orange

#688 add release notes for the 2022-02-09 release
  src/release-notes/v2022.02.09-0.md
Labels: type::docs, team::orange

#692 Adds release notes for 2022-2-11 version of kurl
  src/release-notes/v2022.02.11-0.md
Labels: peer-review-needed, type::docs, team::blue

#695 kots 1.63.0 and associated kURL release notes
  src/release-notes/v2022.02.11-0.md
  src/release-notes/v2022.02.11-1.md
Labels: type::docs, team::blue

#697 add rke2 and k3s options for distribution
  src/components/Kurlsh.js
Labels: team::orange

#698 Change weights to improve website ordering
  src/markdown-pages/add-on-author/index.md
  src/markdown-pages/add-ons/antrea.md
  src/markdown-pages/add-ons/cert-manager.md
  src/markdown-pages/add-ons/collectd.md
  src/markdown-pages/add-ons/containerd.md
  src/markdown-pages/add-ons/contour.md
  src/markdown-pages/add-ons/docker.md
  src/markdown-pages/add-ons/ekco.md
  src/markdown-pages/add-ons/firewalld.md
  src/markdown-pages/add-ons/fluentd.md
  src/markdown-pages/add-ons/goldpinger.md
  src/markdown-pages/add-ons/iptables.md
  src/markdown-pages/add-ons/kotsadm.md
  src/markdown-pages/add-ons/kurl.md
  src/markdown-pages/add-ons/longhorn.md
  src/markdown-pages/add-ons/metrics-server.md
  src/markdown-pages/add-ons/minio.md
  src/markdown-pages/add-ons/openebs.md
  src/markdown-pages/add-ons/prometheus.md
  src/markdown-pages/add-ons/registry.md
  src/markdown-pages/add-ons/rook.md
  src/markdown-pages/add-ons/selinux.md
  src/markdown-pages/add-ons/sonobuoy.md
  src/markdown-pages/add-ons/ufw.md
  src/markdown-pages/add-ons/velero.md
  src/markdown-pages/add-ons/weave.md
  src/markdown-pages/community/core-contributions.md
  src/markdown-pages/community/index.md
  src/markdown-pages/create-installer/add-on-adv-options.md
  src/markdown-pages/create-installer/creating-an-installer-api.md
  src/markdown-pages/create-installer/creating-an-installer-ui.md
  src/markdown-pages/create-installer/host-preflights/block-devices.md
  src/markdown-pages/create-installer/host-preflights/cpu.md
  src/markdown-pages/create-installer/host-preflights/disk-usage.md
  src/markdown-pages/create-installer/host-preflights/host-os.md
  src/markdown-pages/create-installer/host-preflights/host-services.md
  src/markdown-pages/create-installer/host-preflights/http.md
  src/markdown-pages/create-installer/host-preflights/index.md
  src/markdown-pages/create-installer/host-preflights/system-packages.md
  src/markdown-pages/create-installer/host-preflights/tcp-connect.md
  src/markdown-pages/create-installer/host-preflights/tcp-load-balancer.md
  src/markdown-pages/create-installer/host-preflights/tcp-port.md
  src/markdown-pages/create-installer/host-preflights/time.md
  src/markdown-pages/install-with-kurl/adding-nodes.md
  src/markdown-pages/install-with-kurl/advanced-options.md
  src/markdown-pages/install-with-kurl/dedicated-primary.md
  src/markdown-pages/install-with-kurl/host-preflights.md
  src/markdown-pages/install-with-kurl/ipv6.md
  src/markdown-pages/install-with-kurl/load-balancers.md
  src/markdown-pages/install-with-kurl/migrating-csi.md
  src/markdown-pages/install-with-kurl/migrating.md
  src/markdown-pages/install-with-kurl/proxy-installs.md
  src/markdown-pages/install-with-kurl/removing-object-storage.md
  src/markdown-pages/install-with-kurl/system-requirements.md
  src/markdown-pages/introduction/index.md
  src/markdown-pages/introduction/what-kurl-does.md
Labels: type::docs, team::orange

#699 Release notes for v2022.02.17-0
  src/release-notes/v2022.02.17-0.md
Labels: type::docs, team::orange

#704 updated icons for k3s, rke2, and kubeadm
  src/components/Kurlsh.js
  src/images/main_spritesheet.svg
  src/scss/utilities/icons.scss
Labels: type::chore, team::orange

#706 Mark K3s and RKE2 as beta
  src/components/Kurlsh.js
Labels: type::feature, team::orange

#707 Release adding Beta to K3s and RKE2
  src/components/Kurlsh.js
Labels: type::feature, team::orange

#708 Release notes for v2022.02.23-0
  src/release-notes/v2022.02.23-0.md
Labels: peer-review-done, type::docs, team::orange

#709 Release notes for v2022.02.23-0 (#708)
  src/release-notes/v2022.02.23-0.md
Labels: type::docs, team::orange

#710 Fix typo
  src/markdown-pages/add-ons/rke2.md
Labels: type::docs, team::orange

#712 adds docs for kots 1.65.0
  src/release-notes/v2022.02.25-0.md
Labels: peer-review-done, type::docs, team::blue

#714 Release latest docs
  src/markdown-pages/add-ons/rke2.md
  src/release-notes/v2022.02.25-0.md
Labels: type::docs, team::orange

#715 feat(longhorn): add storageOverProvisioningPercentage flag
  src/markdown-pages/add-ons/longhorn.md
  static/versionDetails.json
Labels: type::docs, team::orange

#716 feat(rn): v2022.02.28-0
  src/release-notes/v2022.02.28-0.md
Labels: peer-review-needed, type::docs, team::orange
