Repository replicatedhq/kurl.sh, pull requests merged in 2022-09, with the labels that each got.

#848 Added required Docker version for ubuntu-22.04
  src/markdown-pages/install-with-kurl/system-requirements.md
Labels: type::docs

#862 Fix algolia search
  algolia-config.json
Labels: type::chore

#863 EKCO restart failed envoy pods
  src/markdown-pages/add-ons/ekco.md
Labels: type::bug, bug::normal

#864 Remove single node optimized page
  src/markdown-pages/create-installer/single-node-optimized.md
Labels: type::docs

#868 Inject openebs comment inline
  Makefile
  package.json
  src/components/Kurlsh.js
  src/utils/kurl-yaml-test.js
  src/utils/kurl-yaml.js
  yarn.lock
Labels: type::chore

#869 Release
  Makefile
  package.json
  src/components/Kurlsh.js
  src/utils/kurl-yaml-test.js
  src/utils/kurl-yaml.js
  yarn.lock
Labels: type::chore

#871 Don't bugsnag from dev environment
  .env.development
  gatsby-browser.js
Labels: type::chore

#873 feat: sort components' selects versions
  .babelrc
  jest.config.js
  loadershim.js
  package.json
  src/components/Kurlsh.js
  src/components/__tests__/kurlsh.js
  yarn.lock
Labels: type::feature

#874 feat: sort components' selects versions
  .babelrc
  jest.config.js
  loadershim.js
  package.json
  src/components/Kurlsh.js
  src/components/__tests__/kurlsh.js
  yarn.lock
Labels: type::feature

#876 chore: enable tests during ci
  .github/workflows/algolia-crawl.yaml
  .github/workflows/test.yaml
Labels: type::chore
