Repository replicatedhq/kurl.sh, pull requests merged in 2022-08, with the labels that each got.

#822 Update cis-compliance.md
  src/markdown-pages/install-with-kurl/cis-compliance.md
Labels: type::bug, type::docs

#842 Remove Local Path Provisioner
  src/components/Kurlsh.js
  src/markdown-pages/add-ons/local-path-provisioner.md
  src/markdown-pages/add-ons/longhorn.md
  src/markdown-pages/add-ons/metrics-server.md
  src/markdown-pages/add-ons/minio.md
  src/markdown-pages/add-ons/prometheus.md
  src/markdown-pages/add-ons/registry.md
  src/markdown-pages/add-ons/rke2.md
  src/markdown-pages/add-ons/rook.md
  src/markdown-pages/add-ons/selinux.md
  src/markdown-pages/add-ons/sonobuoy.md
  static/versionDetails.json
Labels: type::feature

#844 Clarify Kube-bench failure
  src/markdown-pages/install-with-kurl/cis-compliance.md
Labels: type::chore, type::docs
