Repository replicatedhq/kurl.sh, pull requests merged in 2022-01, with the labels that each got.

#646 feat(rn): release notes v2022.01.04-0
  src/release-notes/v2022.01.04-0.md
Labels: peer-review-needed, type::docs

#648 feat(rn): release notes v2022.01.05-0
  src/release-notes/v2022.01.05-0.md
Labels: peer-review-needed

#656 document available host preflights types
  src/components/shared/SidebarFileTree.js
  src/markdown-pages/create-installer/host-preflights/block-devices.md
  src/markdown-pages/create-installer/host-preflights/cpu.md
  src/markdown-pages/create-installer/host-preflights/disk-usage.md
  src/markdown-pages/create-installer/host-preflights/host-os.md
  src/markdown-pages/create-installer/host-preflights/host-services.md
  src/markdown-pages/create-installer/host-preflights/http.md
  src/markdown-pages/create-installer/host-preflights/index.md
  src/markdown-pages/create-installer/host-preflights/memory.md
  src/markdown-pages/create-installer/host-preflights/system-packages.md
  src/markdown-pages/create-installer/host-preflights/tcp-connect.md
  src/markdown-pages/create-installer/host-preflights/tcp-load-balancer.md
  src/markdown-pages/create-installer/host-preflights/tcp-port.md
  src/markdown-pages/create-installer/host-preflights/time.md
Labels: peer-review-done

#653 default built-in host preflights docs
  src/markdown-pages/create-installer/host-preflights/index.md
  src/markdown-pages/install-with-kurl/host-preflights.md
  static/versionDetails.json
Labels: peer-review-done, type::docs

#658 feat(rn): release notes 2022.01.18-0
  src/release-notes/v2022.01.18-0.md
Labels: peer-review-needed

#662 v2022.01.21-0 release notes
  src/release-notes/v2022.01.21-0.md
Labels: peer-review-done, type::chore

#663 v2022.01.22-0 Release Notes
  src/release-notes/v2022.01.22-0.md
Labels: type::docs

#664 Release docs to production
  .github/workflows/update-release-notes.yaml
  hack/release-notes.md.tmpl
  src/release-notes/v2022.01.18-0.md
  src/release-notes/v2022.01.21-0.md
  src/release-notes/v2022.01.22-0.md
Labels: type::docs

#665 feature(rn): release notes 2022.01.24-0
  src/release-notes/v2022.01.24-0.md
Labels: peer-review-done, type::docs

#666 feature(preflights): blocking host preflights and naming updates
  src/markdown-pages/add-ons/kurl.md
  src/markdown-pages/create-installer/host-preflights/index.md
  src/markdown-pages/install-with-kurl/advanced-options.md
  src/markdown-pages/install-with-kurl/host-preflights.md
  static/versionDetails.json
Labels: peer-review-done, type::docs

#670 fix release notes automation
  .github/workflows/update-release-notes.yaml
Labels: type::chore

#669 2022.01.25-0 release notes
  src/release-notes/v2022.01.25-0.md
Labels: documentation, peer-review-needed, type::docs

#667 Update latest spec
  src/markdown-pages/install-with-kurl/index.md
Labels: peer-review-done, type::docs

#671 Revert "fix release notes automation"
  .github/workflows/update-release-notes.yaml
Labels: type::chore

#672 Change KOTS version and add link
  src/release-notes/v2022.01.25-0.md
Labels: peer-review-done, type::docs

#668 feat(antrea): better docs for encyrption
  src/markdown-pages/add-ons/antrea.md
Labels: peer-review-done, type::docs

#676 Alphabetize options list
  src/markdown-pages/install-with-kurl/advanced-options.md
Labels: peer-review-done, type::docs

#677 fix typo in ekco docs
  src/markdown-pages/add-ons/ekco.md
Labels: type::docs

#678 release notes for v2022.01.28-0 and v2022.01.28-1
  src/release-notes/v2022.01.28-0.md
  src/release-notes/v2022.01.28-1.md
Labels: peer-review-done, type::docs, team::orange

#679 Release notes to change write latency host preflight
  src/markdown-pages/install-with-kurl/host-preflights.md
  src/release-notes/v2022.01.28-2.md
Labels: peer-review-needed, type::docs, team::orange

#680 Release notes
  src/markdown-pages/add-ons/ekco.md
  src/markdown-pages/install-with-kurl/advanced-options.md
  src/markdown-pages/install-with-kurl/host-preflights.md
  src/release-notes/v2022.01.28-0.md
  src/release-notes/v2022.01.28-1.md
  src/release-notes/v2022.01.28-2.md
Labels: type::docs, team::orange
