Repository replicatedhq/kurl.sh, pull requests merged in 2022-06, with the labels that each got.

#792 Update docker.md
  src/markdown-pages/add-ons/docker.md
Labels: peer-review-done, type::chore, type::docs

#795 Fix link to CONTRIBUTING.md
  src/markdown-pages/community/core-contributions.md
Labels: type::chore, type::docs, team::orange

#797 add 'beta' to aws add-on titles
  README.md
  src/components/Kurlsh.js
  src/components/SupportedAddOns.js
  src/components/shared/SidebarFileTree.js
  src/markdown-pages/add-ons/antrea.md
  src/markdown-pages/add-ons/aws.md
  src/markdown-pages/add-ons/cert-manager.md
  src/markdown-pages/add-ons/collectd.md
  src/markdown-pages/add-ons/containerd.md
  src/markdown-pages/add-ons/contour.md
  src/markdown-pages/add-ons/docker.md
  src/markdown-pages/add-ons/ekco.md
  src/markdown-pages/add-ons/firewalld.md
  src/markdown-pages/add-ons/fluentd.md
  src/markdown-pages/add-ons/goldpinger.md
  src/markdown-pages/add-ons/iptables.md
  src/markdown-pages/add-ons/k3s.md
  src/markdown-pages/add-ons/kotsadm.md
  src/markdown-pages/add-ons/kubernetes.md
  src/markdown-pages/add-ons/kurl.md
  src/markdown-pages/add-ons/longhorn.md
  src/markdown-pages/add-ons/metrics-server.md
  src/markdown-pages/add-ons/minio.md
  src/markdown-pages/add-ons/openebs.md
  src/markdown-pages/add-ons/prometheus.md
  src/markdown-pages/add-ons/registry.md
  src/markdown-pages/add-ons/rke2.md
  src/markdown-pages/add-ons/rook.md
  src/markdown-pages/add-ons/selinux.md
  src/markdown-pages/add-ons/sonobuoy.md
  src/markdown-pages/add-ons/ufw.md
  src/markdown-pages/add-ons/velero.md
  src/markdown-pages/add-ons/weave.md
  src/markdown-pages/create-installer/single-node-optimized.md
Labels: type::chore, team::blue

#796 add local-path-storage to the main kurl.sh page
  src/components/App.js
  src/components/AppVersionCard.js
  src/components/Kurlsh.js
  src/markdown-pages/add-ons/local-path-provisioner.md
  src/markdown-pages/add-ons/longhorn.md
  src/markdown-pages/add-ons/metrics-server.md
  src/markdown-pages/add-ons/minio.md
  src/markdown-pages/add-ons/prometheus.md
  src/markdown-pages/add-ons/registry.md
  src/markdown-pages/add-ons/rke2.md
  src/markdown-pages/add-ons/rook.md
  src/markdown-pages/add-ons/selinux.md
  src/markdown-pages/add-ons/sonobuoy.md
  src/markdown-pages/add-ons/ufw.md
  src/markdown-pages/add-ons/velero.md
  src/markdown-pages/add-ons/weave.md
  static/versionDetails.json
Labels: type::feature, type::docs, team::blue

#794 Update aws.md
  src/markdown-pages/add-ons/aws.md
  static/versionDetails.json
Labels: type::bug, type::docs

#801 Update local-path-provisioner.md
  src/markdown-pages/add-ons/local-path-provisioner.md
  src/markdown-pages/add-ons/velero.md
Labels: type::chore, type::docs

#804 main to release
  src/markdown-pages/add-ons/local-path-provisioner.md
  src/markdown-pages/add-ons/velero.md
Labels: type::chore, type::docs

#800 Update local-path-provisioner.md
  src/markdown-pages/add-ons/local-path-provisioner.md
Labels: type::chore, type::docs

#805 add beta tag to localpv
  src/markdown-pages/add-ons/local-path-provisioner.md
Labels: type::chore

#810 cstor is not supported by kURL in latest OpenEBS
  src/markdown-pages/add-ons/openebs.md
Labels: type::docs

#812 Fix kurl configuration screen
  src/components/Kurlsh.js
  yarn.lock
Labels: type::bug, bug::normal
