Repository replicatedhq/kurl.sh, pull requests merged in 2022-05, with the labels that each got.

#772 Update advanced-options.md
  src/markdown-pages/install-with-kurl/advanced-options.md
Labels: type::bug, type::docs

#774 WAIT FOR RELEASE - docs for resticTimeout config option and velero-restic-timeout cli flag
  src/markdown-pages/add-ons/velero.md
  src/markdown-pages/install-with-kurl/advanced-options.md
  static/versionDetails.json
Labels: type::docs, team::orange

#777 Add aws addon config
  static/versionDetails.json
Labels: type::feature, team::blue

#778 Add aws addon config (#777)
  static/versionDetails.json
Labels: type::feature, team::blue

#785 add aws logo
  src/images/main_spritesheet.svg
  src/scss/utilities/icons.scss
Labels: type::feature, team::blue

#787 add aws to Supported add-ons with new Category Cloud Provider
  src/components/SupportedAddOns.js
Labels: type::chore, team::blue

#786 Update aws.md
  src/markdown-pages/add-ons/aws.md
Labels: peer-review-needed, type::chore, type::docs

#790 ekco-enable-internal-load-balancer flag
  src/markdown-pages/add-ons/ekco.md
  src/markdown-pages/install-with-kurl/advanced-options.md
Labels: type::feature
