Repository replicatedhq/kurl.sh, pull requests merged in 2022-04, with the labels that each got.

#765 release again
  CONTRIBUTING.md
  src/components/Kurlsh.js
  src/markdown-pages/add-ons/ekco.md
  src/markdown-pages/add-ons/kubernetes.md
  src/markdown-pages/install-with-kurl/advanced-options.md
  static/versionDetails.json
Labels: type::docs

#766 kubereserved docs
  src/markdown-pages/add-ons/kubernetes.md
Labels: type::bug, bug::regression, type::docs, team::blue

#768 Update versionDetails.json
  static/versionDetails.json
Labels: peer-review-needed, type::docs

#770 Advanced options private-address
  src/markdown-pages/install-with-kurl/advanced-options.md
Labels: type::docs

#769 Remove support for Ubuntu 16.04
  src/components/App.js
  src/markdown-pages/install-with-kurl/system-requirements.md
Labels: type::chore
