Repository replicatedhq/kurl.sh, pull requests merged in 2022-10, with the labels that each got.

#877 change examples to use k8s 1.25
  src/markdown-pages/create-installer/index.md
  src/markdown-pages/install-with-kurl/index.md
Labels: type::feature

#878 Choosing a PV Provisioner
  src/markdown-pages/create-installer/add-on-adv-options.md
  src/markdown-pages/create-installer/choosing-a-pv-provisioner.md
  src/markdown-pages/create-installer/creating-an-installer-api.md
  src/markdown-pages/create-installer/creating-an-installer-ui.md
  src/markdown-pages/create-installer/host-preflights/block-devices.md
  src/markdown-pages/create-installer/host-preflights/cpu.md
  src/markdown-pages/create-installer/host-preflights/disk-usage.md
  src/markdown-pages/create-installer/host-preflights/filesystem-performance.md
  src/markdown-pages/create-installer/host-preflights/host-os.md
  src/markdown-pages/create-installer/host-preflights/host-services.md
  src/markdown-pages/create-installer/host-preflights/http.md
  src/markdown-pages/create-installer/host-preflights/index.md
  src/markdown-pages/create-installer/host-preflights/memory.md
  src/markdown-pages/create-installer/host-preflights/system-packages.md
  src/markdown-pages/create-installer/host-preflights/tcp-connect.md
  src/markdown-pages/create-installer/host-preflights/tcp-load-balancer.md
  src/markdown-pages/create-installer/host-preflights/tcp-port.md
  src/markdown-pages/create-installer/host-preflights/time.md
Labels: type::chore, type::docs

#879 Release
  .github/workflows/algolia-crawl.yaml
  .github/workflows/test.yaml
  package.json
  src/markdown-pages/create-installer/add-on-adv-options.md
  src/markdown-pages/create-installer/choosing-a-pv-provisioner.md
  src/markdown-pages/create-installer/creating-an-installer-api.md
  src/markdown-pages/create-installer/creating-an-installer-ui.md
  src/markdown-pages/create-installer/host-preflights/block-devices.md
  src/markdown-pages/create-installer/host-preflights/cpu.md
  src/markdown-pages/create-installer/host-preflights/disk-usage.md
  src/markdown-pages/create-installer/host-preflights/filesystem-performance.md
  src/markdown-pages/create-installer/host-preflights/host-os.md
  src/markdown-pages/create-installer/host-preflights/host-services.md
  src/markdown-pages/create-installer/host-preflights/http.md
  src/markdown-pages/create-installer/host-preflights/index.md
  src/markdown-pages/create-installer/host-preflights/memory.md
  src/markdown-pages/create-installer/host-preflights/system-packages.md
  src/markdown-pages/create-installer/host-preflights/tcp-connect.md
  src/markdown-pages/create-installer/host-preflights/tcp-load-balancer.md
  src/markdown-pages/create-installer/host-preflights/tcp-port.md
  src/markdown-pages/create-installer/host-preflights/time.md
  src/markdown-pages/create-installer/index.md
  src/markdown-pages/install-with-kurl/index.md
  src/utils/__tests__/kurl-yaml.js
  src/utils/kurl-yaml.js
Labels: type::chore, type::docs

#840 Update ekco.md
  src/markdown-pages/add-ons/ekco.md
Labels: type::docs

#880 Link to Choosing a PV Provisioner documentation from default spec
  src/utils/__tests__/kurl-yaml.js
  src/utils/kurl-yaml.js
Labels: type::chore, type::docs

#883 Release
  src/markdown-pages/add-ons/ekco.md
  src/utils/__tests__/kurl-yaml.js
  src/utils/kurl-yaml.js
Labels: type::chore

#884 Document ekco.rookShouldDisableReconcileCephCSIResources property
  src/markdown-pages/add-ons/ekco.md
  static/versionDetails.json
Labels: type::chore

#885 Release
  src/markdown-pages/add-ons/ekco.md
  static/versionDetails.json
Labels: type::chore

#886 Netlify deploy workflow
  .github/workflows/deploy.yaml
  .github/workflows/preview.yaml
  .github/workflows/test.yaml
  CODEOWNERS
  README.md
Labels: type::chore

#889 show 'Changing Storage' after 'Removing Object Storage'
  src/markdown-pages/install-with-kurl/changing-storage.md
  src/markdown-pages/install-with-kurl/cis-compliance.md
  src/markdown-pages/install-with-kurl/ipv6.md
Labels: type::chore

#890 feat: show installer object lint error
  src/components/Kurlsh.js
Labels: type::feature

#892 Add Algoalia credentials to environment
  .env.development
  .env.production
  .env.staging
Labels: type::bug, bug::regression

#895 Add monitoring info for Rook add-on
  src/markdown-pages/add-ons/rook.md
  static/ceph-grafana-dashboard.png
Labels: type::feature

#894 Flannel add-on
  src/components/Kurlsh.js
  src/components/__tests__/kurlsh.js
  src/components/modals/ConfirmSelectionModal.js
  src/markdown-pages/add-ons/flannel.md
  src/markdown-pages/install-with-kurl/index.md
  static/versionDetails.json
Labels: type::feature

#897 Default to top item in dropdown rather than latest when selected
  src/components/Kurlsh.js
Labels: type::bug, bug::normal

#899 Reuse code for AddOnWrapper shared component
  src/components/AddOnWrapper.js
  src/components/Kurlsh.js
  src/components/shared/AddOnWrapper.js
Labels: type::chore

#900 Remove RKE2 and K3s documentation
  src/components/Kurlsh.js
  src/components/__tests__/kurlsh.js
  src/markdown-pages/add-ons/aws.md
  src/markdown-pages/add-ons/k3s.md
  src/markdown-pages/add-ons/kubernetes.md
  src/markdown-pages/add-ons/rke2.md
  src/markdown-pages/introduction/index.md
  src/markdown-pages/introduction/what-kurl-does.md
Labels: type::feature

#901 Document Rook to OpenEBS Data Migration is Now Supported
  src/markdown-pages/install-with-kurl/migrating-csi.md
  src/markdown-pages/install-with-kurl/migrating.md
Labels: type::feature
