Repository replicatedhq/kurl.sh, pull requests merged in 2023-06, with the labels that each got.

#981 doc: document small changes on how proxy is configured
  src/markdown-pages/install-with-kurl/proxy-installs.md
Labels: type::chore

#983 doc: add notes on weave to flannel migration
  src/markdown-pages/add-ons/flannel.md
Labels: type::feature, type::docs

#986 Fix netlifly preview
  .github/workflows/preview.yaml
Labels: type::chore

#984 Update system-requirements.md - Add support to RHEL 8.8
  src/markdown-pages/install-with-kurl/system-requirements.md
Labels: documentation, type::feature, type::docs

#985 Update App.js - To add missing supported OS
  src/components/App.js
Labels: type::feature, type::docs

#990 feat: Display minimumNodeCount under Rook add-on show config
  src/markdown-pages/add-ons/rook.md
  static/versionDetails.json
Labels: type::feature
