Repository replicatedhq/kurl.sh, pull requests merged in 2023-04, with the labels that each got.

#947 feat: support for rhel 9 variants
  src/components/App.js
  src/markdown-pages/add-ons/collectd.md
  src/markdown-pages/add-ons/containerd.md
  src/markdown-pages/add-ons/kubernetes.md
  src/markdown-pages/add-ons/longhorn.md
  src/markdown-pages/add-ons/openebs.md
  src/markdown-pages/add-ons/rook.md
  src/markdown-pages/add-ons/velero.md
  src/markdown-pages/create-installer/host-preflights/system-packages.md
  src/markdown-pages/install-with-kurl/system-requirements.md
Labels: type::feature

#952 doc: documenting containerd upgrade constraints.
  src/markdown-pages/add-ons/containerd.md
  src/markdown-pages/install-with-kurl/upgrading.md
Labels: type::feature, type::docs

#956 chore: fixed typo.
  src/markdown-pages/install-with-kurl/upgrading.md
Labels: type::chore

#957 ekco is mandatory
  src/markdown-pages/add-ons/ekco.md
Labels: type::chore, type::docs

#960 ecko should be ekco
  src/markdown-pages/install-with-kurl/managing-nodes.md
Labels: type::chore, type::docs

#959 feat: upgrade kubernetes multiple versions
  src/markdown-pages/install-with-kurl/upgrading.md
Labels: type::feature

#961 feat(kubernetes): kubernetes upgrade supplemental package prompt example
  src/markdown-pages/install-with-kurl/upgrading.md
Labels: type::feature

#962 Update system-requirements.md - kURL Firewall Openings
  src/markdown-pages/install-with-kurl/system-requirements.md
Labels: type::feature, type::docs

#963 chore: remove rook-upgrade task docs
  src/markdown-pages/add-ons/rook.md
Labels: type::chore
