Repository replicatedhq/kurl.sh, pull requests merged in 2023-05, with the labels that each got.

#964 feat: ability to ignore kubeadm upgrade errors
  src/markdown-pages/install-with-kurl/advanced-options.md
  static/versionDetails.json
Labels: type::feature

#965 feat(kubernetes): configure max pods per node
  src/markdown-pages/install-with-kurl/advanced-options.md
  static/versionDetails.json
Labels: type::feature

#966 Fix typo in "respectively"
  src/markdown-pages/install-with-kurl/system-requirements.md
Labels: type::chore

#967 feat(rook): per node device configuration
  src/markdown-pages/add-ons/rook.md
  static/versionDetails.json
Labels: type::feature

#969 chore: add dependabot for github actions dependencies
  .github/dependabot.yaml
Labels: type::chore

#976 chore(actions): deprecate set-output
  .github/workflows/update-release-notes.yaml
Labels: type::chore

#977 Update system-requirements.md to add Oracle Linux 8.8
  src/markdown-pages/install-with-kurl/system-requirements.md
Labels: documentation, type::feature, type::docs

#978 Update system-requirements.md to add support for Rocky 9.2
  src/markdown-pages/install-with-kurl/system-requirements.md
Labels: type::feature, type::docs
