Repository replicatedhq/kurl.sh, pull requests merged in 2023-02, with the labels that each got.

#935 chore: remove flannel beta designation, make default cni
  src/components/App.js
  src/components/Kurlsh.js
  src/markdown-pages/add-ons/flannel.md
  src/markdown-pages/add-ons/kotsadm.md
  src/markdown-pages/create-installer/host-preflights/index.md
  src/markdown-pages/create-installer/index.md
  src/markdown-pages/install-with-kurl/cis-compliance.md
  src/markdown-pages/install-with-kurl/index.md
  src/markdown-pages/install-with-kurl/ipv6.md
  src/markdown-pages/install-with-kurl/migrating-csi.md
  src/markdown-pages/install-with-kurl/migrating.md
  src/markdown-pages/install-with-kurl/removing-object-storage.md
  src/markdown-pages/install-with-kurl/system-requirements.md
  src/markdown-pages/introduction/index.md
  src/markdown-pages/introduction/what-kurl-does.md
Labels: type::chore

#937 chore: improve disk space requirements docs
  src/components/App.js
  src/markdown-pages/add-ons/rook.md
  src/markdown-pages/install-with-kurl/managing-nodes.md
  src/markdown-pages/install-with-kurl/system-requirements.md
Labels: type::chore

#928 document weave-to-flannel migration
  src/markdown-pages/add-ons/flannel.md
Labels: type::feature

#938 add hostname and IP address requirements
  src/markdown-pages/install-with-kurl/system-requirements.md
Labels: echoes/effort: XS, type::chore, type::docs

#936 doc: adding Longhorn to OpenEBS/Rook migration documentation.
  src/markdown-pages/install-with-kurl/migrating-csi.md
  src/markdown-pages/install-with-kurl/migrating.md
Labels: type::feature, type::docs

#940 fix(flannel): document packet filtering firewall requirements for flannel
  src/markdown-pages/add-ons/flannel.md
  src/markdown-pages/install-with-kurl/system-requirements.md
Labels: type::chore

#941 doc: adding note on kurl version (longhorn migration).
  src/markdown-pages/install-with-kurl/migrating-csi.md
Labels: type::chore

#944 change openebs localpv storageclass name to 'local' from 'default'
  src/markdown-pages/add-ons/kotsadm.md
  src/markdown-pages/add-ons/openebs.md
  src/markdown-pages/create-installer/choosing-a-pv-provisioner.md
  src/markdown-pages/install-with-kurl/migrating-csi.md
  src/markdown-pages/install-with-kurl/migrating.md
  src/markdown-pages/install-with-kurl/removing-object-storage.md
  src/utils/__tests__/kurl-yaml.js
  static/versionDetails.json
Labels: type::chore, type::docs

#946 feat: enable austere linter for kurl.sh.
  src/components/Kurlsh.js
Labels: type::feature

#945 Fix info regards Container Runtimes
  src/markdown-pages/install-with-kurl/upgrading.md
Labels: type::bug, bug::normal
