Repository replicatedhq/kurl.sh, pull requests merged in 2024-09, with the labels that each got.

#1030 Add Ubuntu 24.04 and AL 2023
  src/markdown-pages/install-with-kurl/system-requirements.md
Labels: type::feature

#1036 Address CVEs
  package.json
  yarn.lock
Labels: type::security

#1038 Address HIGH CVEs
  package.json
  yarn.lock
Labels: type::security

#1039 chore: update cis docs to meet 1.8 benchmarks
  src/markdown-pages/install-with-kurl/cis-compliance.md
Labels: type::chore
