Repository replicatedhq/kurl.sh, pull requests merged in 2024-12, with the labels that each got.

#1045 update the system requirements page to include the latest RHEL
  src/components/App.js
  src/markdown-pages/install-with-kurl/system-requirements.md
Labels: type::chore

#1046 Updating dependencies
  .github/workflows/deploy.yaml
  .github/workflows/preview.yaml
  .github/workflows/test.yaml
  Makefile
  gatsby-config.js
  gatsby-node.js
  package.json
  src/components/DownloadAirgapBundle.js
  src/components/Kurlsh.js
  src/components/Sidebar.js
  src/components/SidebarReleaseNotes.js
  src/components/shared/Footer.js
  src/components/shared/MobileNavBar.js
  src/components/shared/NavBar.js
  src/components/shared/SidebarFileTree.js
  src/templates/ReleaseNotesListTemplate.js
  yarn.lock
Labels: type::chore

#1048 Adding the playwrite install to the prod deploy step
  .github/workflows/deploy.yaml
Labels: type::chore

#1047 Reenable dependabot for kurl.sh
  .github/dependabot.yaml
Labels: type::chore

#1074 Remove warning
  src/markdown-pages/install-with-kurl/managing-nodes.md
Labels: type::feature, type::docs

#1080 Update proxy-installs.md explain parameters
  src/markdown-pages/install-with-kurl/proxy-installs.md
Labels: type::chore, type::docs
